"""Leakage-resistant modeling contracts for Parallax."""

from parallax.modeling.baselines import (
    BASELINE_EXPERIMENT_SCHEMA_VERSION,
    CATEGORY_LABELS,
    BaselineConfig,
    BaselineExperimentResult,
    BaselineModel,
    BaselineModelingError,
    CategoryMetrics,
    ClassificationMetrics,
    TrainedBaseline,
    fit_initial_baselines,
)
from parallax.modeling.dataset import (
    MODELING_DATASET_SCHEMA_VERSION,
    FeaturePartition,
    ModelingDatasetError,
    PartitionedFeatureDataset,
    load_partitioned_feature_dataset,
)
from parallax.modeling.episodes import (
    CATEGORY_TO_INDEX,
    EPISODIC_SAMPLER_SCHEMA_VERSION,
    EpisodeConfig,
    EpisodeSamplingError,
    PrototypeEpisode,
    TrainingEpisodeSampler,
)
from parallax.modeling.prototypes import (
    DROPOUT_PROBABILITY,
    EMBEDDING_DIMENSION,
    HIDDEN_DIMENSION,
    PROTOTYPE_MODEL_SCHEMA_VERSION,
    TRAFFIC_CATEGORY_COUNT,
    PrototypeEmbeddingNetwork,
    PrototypeModelingError,
    calculate_class_prototypes,
    prototype_probabilities,
    prototypical_cross_entropy,
    squared_euclidean_logits,
)
from parallax.modeling.report import (
    BASELINE_VALIDATION_REPORT_SCHEMA_VERSION,
    BaselineValidationReport,
    BaselineValidationReportError,
    export_baseline_validation_report,
)
from parallax.modeling.training import (
    ADAM_BETA_1,
    ADAM_BETA_2,
    ADAM_EPSILON,
    PROTOTYPE_TRAINING_SCHEMA_VERSION,
    PrototypeTrainingConfig,
    PrototypeTrainingError,
    PrototypeTrainingResult,
    fit_prototype_embedding,
)

__all__ = [
    "ADAM_BETA_1",
    "ADAM_BETA_2",
    "ADAM_EPSILON",
    "BASELINE_EXPERIMENT_SCHEMA_VERSION",
    "BASELINE_VALIDATION_REPORT_SCHEMA_VERSION",
    "CATEGORY_LABELS",
    "CATEGORY_TO_INDEX",
    "DROPOUT_PROBABILITY",
    "EMBEDDING_DIMENSION",
    "EPISODIC_SAMPLER_SCHEMA_VERSION",
    "HIDDEN_DIMENSION",
    "MODELING_DATASET_SCHEMA_VERSION",
    "PROTOTYPE_MODEL_SCHEMA_VERSION",
    "PROTOTYPE_TRAINING_SCHEMA_VERSION",
    "TRAFFIC_CATEGORY_COUNT",
    "BaselineConfig",
    "BaselineExperimentResult",
    "BaselineModel",
    "BaselineModelingError",
    "BaselineValidationReport",
    "BaselineValidationReportError",
    "CategoryMetrics",
    "ClassificationMetrics",
    "EpisodeConfig",
    "EpisodeSamplingError",
    "FeaturePartition",
    "ModelingDatasetError",
    "PartitionedFeatureDataset",
    "PrototypeEmbeddingNetwork",
    "PrototypeEpisode",
    "PrototypeModelingError",
    "PrototypeTrainingConfig",
    "PrototypeTrainingError",
    "PrototypeTrainingResult",
    "TrainedBaseline",
    "TrainingEpisodeSampler",
    "calculate_class_prototypes",
    "export_baseline_validation_report",
    "fit_initial_baselines",
    "fit_prototype_embedding",
    "load_partitioned_feature_dataset",
    "prototype_probabilities",
    "prototypical_cross_entropy",
    "squared_euclidean_logits",
]
