"""Versioned feature contracts and numerical transforms for Parallax."""

from parallax.features.calculator import (
    FeatureCalculationConfig,
    build_directional_size_signals,
    calculate_feature_vector,
)
from parallax.features.export import (
    FEATURE_ARTIFACT_SCHEMA_VERSION,
    FEATURE_PARQUET_SCHEMA,
    RELEASE_COMPATIBLE_WINDOW_SHA256,
    FeatureExportError,
    FeatureExportReport,
    FeatureExportSummary,
    export_vnat_features,
)
from parallax.features.flow_statistics import (
    ACTIVITY_TIMEOUT_SECONDS,
    AGGREGATE_LOG_EPSILON,
    ByteTotalPolicy,
    calculate_active_idle_feature_vector,
    calculate_aggregate_feature_vector,
    calculate_interarrival_feature_vector,
)
from parallax.features.runtime import (
    VnatWindowFeature,
    extract_vnat_pcap_features,
)
from parallax.features.schema import (
    FEATURE_COLUMNS,
    FEATURE_SCHEMA_VERSION,
    FLOW_STATISTIC_COLUMNS,
    STATIONARY_WAVELET_LEVEL,
    WAVELET_BAND_COUNT,
    WAVELET_FEATURE_COLUMNS,
    WAVELET_NAME,
    WINDOW_SAMPLE_COUNT,
    FeatureContractError,
    normalize_feature_vector,
)
from parallax.features.split_manifest import (
    CAPTURE_SPLIT_MANIFEST_SCHEMA_VERSION,
    RELEASE_COMPATIBLE_CAPTURE_SPLIT_MANIFEST_SHA256,
    RELEASE_COMPATIBLE_CAPTURE_SPLIT_MANIFEST_SIZE_BYTES,
    RELEASE_COMPATIBLE_FEATURE_ARTIFACT_SHA256,
    RELEASE_COMPATIBLE_FEATURE_ARTIFACT_SIZE_BYTES,
    CaptureSplitManifestError,
    CaptureSplitManifestReport,
    export_capture_split_manifest,
)
from parallax.features.wavelets import (
    WAVELET_LOG_EPSILON,
    DirectionalWaveletFeatures,
    WaveletNormalization,
    calculate_directional_wavelet_features,
    calculate_wavelet_feature_vector,
    stationary_haar_bands,
)

__all__ = [
    "ACTIVITY_TIMEOUT_SECONDS",
    "AGGREGATE_LOG_EPSILON",
    "CAPTURE_SPLIT_MANIFEST_SCHEMA_VERSION",
    "FEATURE_ARTIFACT_SCHEMA_VERSION",
    "FEATURE_COLUMNS",
    "FEATURE_PARQUET_SCHEMA",
    "FEATURE_SCHEMA_VERSION",
    "FLOW_STATISTIC_COLUMNS",
    "RELEASE_COMPATIBLE_CAPTURE_SPLIT_MANIFEST_SHA256",
    "RELEASE_COMPATIBLE_CAPTURE_SPLIT_MANIFEST_SIZE_BYTES",
    "RELEASE_COMPATIBLE_FEATURE_ARTIFACT_SHA256",
    "RELEASE_COMPATIBLE_FEATURE_ARTIFACT_SIZE_BYTES",
    "RELEASE_COMPATIBLE_WINDOW_SHA256",
    "STATIONARY_WAVELET_LEVEL",
    "WAVELET_BAND_COUNT",
    "WAVELET_FEATURE_COLUMNS",
    "WAVELET_LOG_EPSILON",
    "WAVELET_NAME",
    "WINDOW_SAMPLE_COUNT",
    "ByteTotalPolicy",
    "CaptureSplitManifestError",
    "CaptureSplitManifestReport",
    "DirectionalWaveletFeatures",
    "FeatureCalculationConfig",
    "FeatureContractError",
    "FeatureExportError",
    "FeatureExportReport",
    "FeatureExportSummary",
    "VnatWindowFeature",
    "WaveletNormalization",
    "build_directional_size_signals",
    "calculate_active_idle_feature_vector",
    "calculate_aggregate_feature_vector",
    "calculate_directional_wavelet_features",
    "calculate_feature_vector",
    "calculate_interarrival_feature_vector",
    "calculate_wavelet_feature_vector",
    "export_capture_split_manifest",
    "export_vnat_features",
    "extract_vnat_pcap_features",
    "normalize_feature_vector",
    "stationary_haar_bands",
]
